repos:
  - repo: local
    hooks:
      - id: poe-lint
        name: Lintting
        entry: poe lint
        language: system
        types: [python]

      - id: poe-format
        name: Formatting
        entry: poe format
        language: system
        types: [python]

      # - id: pytest
      #   name: Pytest
      #   entry: pytest
      #   language: system
      #   types: [python]
